# Generated by Django 4.1.3 on 2022-12-07 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('TNK', 'Танки'), ('HIL', 'Хиллы'), ('DD', 'DD'), ('DLR', 'Торговцы'), ('GMR', 'Гилдмастеры'), ('QGR', 'Квестгиверы'), ('BST', 'Кузнецы'), ('TNR', 'Кожевники'), ('PMR', 'Зельевары'), ('SMR', 'Мастеры заклинаний')], max_length=3, verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='picture',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardApp.profile', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='videoLink',
            field=models.CharField(max_length=255, verbose_name='Ссылка на видео'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
