# Generated by Django 4.1.3 on 2022-12-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('tanks', 'Танки'), ('hills', 'Хиллы'), ('DD', 'DD'), ('dealers', 'Торговцы'), ('gildmasters', 'Гилдмастеры'), ('questgivers', 'Квестгиверы'), ('blacksmith', 'Кузнецы'), ('tanner', 'Кожевники'), ('potionMaster', 'Зельевары'), ('spellMaster', 'Мастеры заклинаний')], default='TNK', max_length=15),
        ),
    ]
