# Generated by Django 4.1.3 on 2022-12-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardApp', '0002_alter_ad_category_alter_ad_picture_alter_ad_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('TNK', 'Танки'), ('HIL', 'Хиллы'), ('DD', 'DD'), ('DLR', 'Торговцы'), ('GMR', 'Гилдмастеры'), ('QGR', 'Квестгиверы'), ('BST', 'Кузнецы'), ('TNR', 'Кожевники'), ('PMR', 'Зельевары'), ('SMR', 'Мастеры заклинаний')], default='TNK', max_length=3, verbose_name='Категории'),
        ),
    ]
