# Generated by Django 4.1.3 on 2022-12-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardApp', '0003_alter_ad_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='videoLink',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
