# Generated by Django 4.1.3 on 2022-12-08 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardApp', '0004_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(default='Танки', on_delete=django.db.models.deletion.CASCADE, to='boardApp.category', verbose_name='Категории'),
        ),
    ]
