# Generated by Django 4.1.3 on 2022-12-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardApp', '0006_ad_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(help_text='Заголовок объявления', max_length=255, verbose_name='Заголовок'),
        ),
    ]
