# Generated by Django 4.1.3 on 2022-12-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardApp', '0008_alter_ad_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Изображение'),
        ),
    ]
